name: Validate

on:
  pull_request:
    branches: [master]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.1-jammy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node v18
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install node_modules
        run: npm ci
      - name: Validate frontend
        run: npm run prepackage
